import { prisma } from "./config/prisma.js";

const mockHotels = [
  {
    id: "h1",
    name: "Luxury Palace Hotel",
    city: "Ho Chi Minh City",
    district: "District 1",
    address: "123 Nguyen Hue, District 1, HCMC",
    description: "Experience the ultimate luxury in the heart of the city.",
    price: 150.0,
    rating: 4.8,
    reviewScore: 9.2,
    reviewCount: 1250,
    category: "Hotel",
    distanceToCenter: 0.5,
    nearPublicTransport: true,
    petFriendly: false,
    maxAdults: 2,
    maxKids: 1,
    bedrooms: 1,
    amenities: ["Pool", "Spa", "Gym", "Restaurant", "Bar", "Free WiFi"],
    roomFeatures: ["Air Conditioning", "Balcony", "Bathtub", "Mini Bar"],
    policies: ["Non-smoking", "No pets allowed", "Check-in from 14:00", "Check-out until 12:00"],
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    latitude: 10.7743,
    longitude: 106.7044,
  },
  {
    id: "h2",
    name: "Cozy Boutique Stay",
    city: "Da Lat",
    district: "Ward 3",
    address: "45 Ba Trieu, Ward 3, Da Lat",
    description: "A charming boutique hotel surrounded by pine trees.",
    price: 45.0,
    rating: 4.5,
    reviewScore: 8.8,
    reviewCount: 420,
    category: "Homestay",
    distanceToCenter: 1.2,
    nearPublicTransport: false,
    petFriendly: true,
    maxAdults: 4,
    maxKids: 2,
    bedrooms: 2,
    amenities: ["Free Breakfast", "Garden", "Fireplace", "Free WiFi"],
    roomFeatures: ["Mountain View", "Heater", "Private Bathroom"],
    policies: ["Pet friendly", "Smoking allowed in designated areas"],
    images: ["https://images.unsplash.com/photo-1542314831-c6a4d1409e1c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    latitude: 11.9404,
    longitude: 108.4583,
  },
  {
    id: "h3",
    name: "Vinpearl Resort & Spa",
    city: "Nha Trang",
    district: "Hon Tre",
    address: "Hon Tre Island, Nha Trang",
    description: "A 5-star island resort offering an exclusive private beach and premium spa services.",
    price: 250.0,
    rating: 4.9,
    reviewScore: 9.6,
    reviewCount: 3100,
    category: "Resort",
    distanceToCenter: 5.0,
    nearPublicTransport: false,
    petFriendly: false,
    maxAdults: 2,
    maxKids: 2,
    bedrooms: 1,
    amenities: ["Private Beach", "Pool", "Spa", "Kids Club", "Fine Dining", "Golf Course"],
    roomFeatures: ["Ocean View", "Air Conditioning", "Balcony", "Bathtub", "Mini Bar"],
    policies: ["Non-smoking", "No pets allowed", "Check-in from 14:00", "Check-out until 12:00"],
    images: ["https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    latitude: 12.2178,
    longitude: 109.2415,
  },
  {
    id: "h4",
    name: "InterContinental Hanoi Landmark72",
    city: "Hanoi",
    district: "Nam Tu Liem",
    address: "Keangnam Landmark72, Pham Hung, Hanoi",
    description: "The highest luxury hotel in Hanoi offering panoramic city views.",
    price: 180.0,
    rating: 4.7,
    reviewScore: 9.4,
    reviewCount: 2200,
    category: "Hotel",
    distanceToCenter: 7.5,
    nearPublicTransport: true,
    petFriendly: false,
    maxAdults: 2,
    maxKids: 1,
    bedrooms: 1,
    amenities: ["Pool", "Spa", "Gym", "Restaurant", "Club Lounge", "Free WiFi"],
    roomFeatures: ["City View", "Air Conditioning", "Bathtub", "Mini Bar"],
    policies: ["Non-smoking", "Check-in from 15:00", "Check-out until 12:00"],
    images: ["https://images.unsplash.com/photo-1551882547-ff40eb0d1b73?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    latitude: 21.0175,
    longitude: 105.7845,
  },
  {
    id: "h5",
    name: "Pullman Vung Tau",
    city: "Vung Tau",
    district: "Thang Tam",
    address: "15 Thi Sach, Thang Tam Ward, Vung Tau",
    description: "A premium 5-star hotel offering stunning ocean views.",
    price: 120.0,
    rating: 4.6,
    reviewScore: 9.0,
    reviewCount: 1540,
    category: "Hotel",
    distanceToCenter: 2.1,
    nearPublicTransport: true,
    petFriendly: false,
    maxAdults: 2,
    maxKids: 2,
    bedrooms: 1,
    amenities: ["Pool", "Private Beach", "Bar", "Free WiFi"],
    roomFeatures: ["Ocean View", "Balcony", "Air Conditioning"],
    policies: ["Non-smoking", "Check-in from 15:00", "Check-out until 12:00"],
    images: ["https://images.unsplash.com/photo-1578683010236-d716f9a3f461?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    latitude: 10.3458,
    longitude: 107.0945,
  },
  {
    id: "h6",
    name: "JW Marriott Phu Quoc",
    city: "Phu Quoc",
    district: "An Thoi",
    address: "Khem Beach, An Thoi, Phu Quoc",
    description: "A whimsical luxury resort designed by Bill Bensley.",
    price: 350.0,
    rating: 4.9,
    reviewScore: 9.8,
    reviewCount: 4200,
    category: "Resort",
    distanceToCenter: 15.0,
    nearPublicTransport: false,
    petFriendly: false,
    maxAdults: 2,
    maxKids: 2,
    bedrooms: 1,
    amenities: ["Private Beach", "Spa", "Pool", "Gym", "Fine Dining"],
    roomFeatures: ["Ocean View", "Balcony", "Bathtub", "Mini Bar"],
    policies: ["Non-smoking", "Check-in from 15:00", "Check-out until 12:00"],
    images: ["https://images.unsplash.com/photo-1582719508461-905c673771fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    latitude: 10.0384,
    longitude: 104.0298,
  },
  {
    id: "h7",
    name: "Sun & Sea Apartment",
    city: "Da Nang",
    district: "Son Tra",
    address: "220 Vo Nguyen Giap, Son Tra, Da Nang",
    description: "A premier beachfront resort in Da Nang, perfect for family vacations and relaxation.",
    price: 220.0,
    rating: 4.8,
    reviewScore: 9.5,
    reviewCount: 2800,
    category: "Resort",
    distanceToCenter: 4.0,
    nearPublicTransport: false,
    petFriendly: false,
    maxAdults: 4,
    maxKids: 2,
    bedrooms: 2,
    amenities: ["Beachfront", "Pool", "Spa", "Gym", "Restaurant", "Bar"],
    roomFeatures: ["Ocean View", "Air Conditioning", "Balcony", "Bathtub", "Mini Bar"],
    policies: ["Non-smoking", "Check-in from 14:00", "Check-out until 11:00"],
    images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    latitude: 16.0357,
    longitude: 108.2505,
  },
  {
    id: "h8",
    name: "Rex Hotel Saigon",
    city: "Ho Chi Minh City",
    district: "District 1",
    address: "141 Nguyen Hue, Ben Nghe, District 1, Ho Chi Minh City",
    description: "A heritage hotel located in the heart of Saigon, featuring timeless architecture and rooftop bar.",
    price: 130.0,
    rating: 4.5,
    reviewScore: 8.9,
    reviewCount: 3400,
    category: "Hotel",
    distanceToCenter: 0.1,
    nearPublicTransport: true,
    petFriendly: false,
    maxAdults: 2,
    maxKids: 1,
    bedrooms: 1,
    amenities: ["Pool", "Spa", "Gym", "Restaurant", "Rooftop Bar", "Free WiFi"],
    roomFeatures: ["City View", "Air Conditioning", "Bathtub", "Heritage Decor"],
    policies: ["Non-smoking", "Check-in from 14:00", "Check-out until 12:00"],
    images: ["https://images.unsplash.com/photo-1542314831-c6a4d1409e1c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    latitude: 10.7761,
    longitude: 106.7022,
  },
  {
    id: "h9",
    name: "Melia Hanoi",
    city: "Hanoi",
    district: "Hoan Kiem",
    address: "44B Ly Thuong Kiet, Tran Hung Dao, Hoan Kiem, Hanoi",
    description: "Situated right in the city center, offering breathtaking views of the city skyline and luxurious amenities.",
    price: 160.0,
    rating: 4.7,
    reviewScore: 9.3,
    reviewCount: 2900,
    category: "Hotel",
    distanceToCenter: 1.0,
    nearPublicTransport: true,
    petFriendly: false,
    maxAdults: 2,
    maxKids: 2,
    bedrooms: 1,
    amenities: ["Pool", "Spa", "Gym", "Restaurant", "Business Center"],
    roomFeatures: ["City View", "Air Conditioning", "Bathtub", "Mini Bar"],
    policies: ["Non-smoking", "Check-in from 14:00", "Check-out until 12:00"],
    images: ["https://images.unsplash.com/photo-1578683010236-d716f9a3f461?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    latitude: 21.0233,
    longitude: 105.8475,
  },
  {
    id: "h10",
    name: "Muong Thanh Luxury Da Nang",
    city: "Da Nang",
    district: "Ngu Hanh Son",
    address: "270 Vo Nguyen Giap, Bac My Phu, Ngu Hanh Son, Da Nang",
    description: "A 5-star beachfront hotel providing the finest hospitality experience in Da Nang.",
    price: 100.0,
    rating: 4.4,
    reviewScore: 8.7,
    reviewCount: 1500,
    category: "Hotel",
    distanceToCenter: 5.5,
    nearPublicTransport: true,
    petFriendly: false,
    maxAdults: 2,
    maxKids: 2,
    bedrooms: 1,
    amenities: ["Beachfront", "Pool", "Spa", "Gym", "Restaurant"],
    roomFeatures: ["Ocean View", "Air Conditioning", "Balcony"],
    policies: ["Non-smoking", "Check-in from 14:00", "Check-out until 12:00"],
    images: ["https://images.unsplash.com/photo-1551882547-ff40eb0d1b73?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    latitude: 16.0506,
    longitude: 108.2464,
  }
];

const mockRoomTypes = [
  {
    id: "rt1",
    hotelId: "h1",
    name: "Phòng Gia Đình Hướng Biển",
    description: "Phòng rộng rãi với tầm nhìn hướng biển tuyệt đẹp",
    basePrice: 150.0,
    maxAdults: 4,
    maxKids: 2,
    bedrooms: 2,
    beds: ["1 King Bed", "2 Single Beds"],
    amenities: ["Free WiFi", "Bathtub", "Ocean View", "Balcony"],
    images: ["https://images.unsplash.com/photo-1611892440504-42a792e24d32?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    totalInventory: 3
  },
  {
    id: "rt1_single",
    hotelId: "h1",
    name: "Phòng Đơn (Single Room)",
    description: "Phòng tiêu chuẩn dành cho 1-2 người",
    basePrice: 50.0,
    maxAdults: 2,
    maxKids: 1,
    bedrooms: 1,
    beds: ["1 Queen Bed"],
    amenities: ["Free WiFi", "City View"],
    images: ["https://images.unsplash.com/photo-1590490360182-c33d57733427?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    totalInventory: 10
  },
  {
    id: "rt1_double",
    hotelId: "h1",
    name: "Phòng Đôi (Double Room)",
    description: "Phòng rộng rãi dành cho cặp đôi hoặc gia đình nhỏ",
    basePrice: 85.0,
    maxAdults: 2,
    maxKids: 2,
    bedrooms: 1,
    beds: ["1 King Bed"],
    amenities: ["Free WiFi", "City View", "Bathtub"],
    images: ["https://images.unsplash.com/photo-1590490360182-c33d57733427?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    totalInventory: 8
  },
  {
    id: "rt2",
    hotelId: "h2",
    name: "Phòng Tiêu Chuẩn Hướng Phố",
    description: "Phòng thoải mái với tầm nhìn ra thành phố",
    basePrice: 80.0,
    maxAdults: 2,
    maxKids: 0,
    bedrooms: 1,
    beds: ["1 Queen Bed"],
    amenities: ["Free WiFi", "City View"],
    images: ["https://images.unsplash.com/photo-1590490360182-c33d57733427?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    totalInventory: 5
  }
];

const generatedRoomTypes: any[] = [];
for (const hotel of mockHotels) {
  generatedRoomTypes.push({
    id: `${hotel.id}_single`,
    hotelId: hotel.id,
    name: "Phòng Đơn (Single Room)",
    description: "Phòng tiêu chuẩn dành cho 1-2 người",
    basePrice: hotel.price * 0.5,
    maxAdults: 2,
    maxKids: 1,
    bedrooms: 1,
    beds: ["1 Queen Bed"],
    amenities: ["Free WiFi", "City View"],
    images: ["https://images.unsplash.com/photo-1590490360182-c33d57733427?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    totalInventory: 10
  });
  generatedRoomTypes.push({
    id: `${hotel.id}_double`,
    hotelId: hotel.id,
    name: "Phòng Đôi (Double Room)",
    description: "Phòng rộng rãi dành cho cặp đôi",
    basePrice: hotel.price * 0.8,
    maxAdults: 2,
    maxKids: 2,
    bedrooms: 1,
    beds: ["1 King Bed"],
    amenities: ["Free WiFi", "City View", "Bathtub"],
    images: ["https://images.unsplash.com/photo-1590490360182-c33d57733427?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    totalInventory: 8
  });
  generatedRoomTypes.push({
    id: `${hotel.id}_family`,
    hotelId: hotel.id,
    name: "Phòng Gia Đình",
    description: "Phòng rộng rãi dành cho gia đình",
    basePrice: hotel.price * 1.5,
    maxAdults: 4,
    maxKids: 2,
    bedrooms: 2,
    beds: ["1 King Bed", "2 Single Beds"],
    amenities: ["Free WiFi", "Bathtub", "Balcony"],
    images: ["https://images.unsplash.com/photo-1611892440504-42a792e24d32?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80"],
    totalInventory: 3
  });
}

async function main() {
  console.log("Start seeding...");
  for (const hotel of mockHotels) {
    const hotelData = {
      name: hotel.name,
      slug: hotel.name.toLowerCase().replace(/\s+/g, '-'),
      ownerId: '11111111-1111-1111-1111-111111111111',
      description: hotel.description,
      address: hotel.address,
      city: hotel.city,
      country: 'Vietnam',
      latitude: hotel.latitude,
      longitude: hotel.longitude,
      amenities: hotel.amenities,
      rating: hotel.rating,
    };
    await prisma.hotel.upsert({
      where: { id: hotel.id },
      update: hotelData,
      create: {
        id: hotel.id,
        ...hotelData
      },
    });
  }

  const allRoomTypes = [...mockRoomTypes, ...generatedRoomTypes];
  const uniqueRoomTypes = Array.from(new Map(allRoomTypes.map(rt => [rt.id, rt])).values());

  for (const rt of uniqueRoomTypes) {
    await prisma.roomType.upsert({
      where: { id: rt.id },
      update: rt,
      create: rt,
    });
  }
  console.log("Seeding finished.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
