import { Router } from 'express';
import * as hotelController from '../controllers/hotel.controller.js';
const router = Router();
router.post('/', hotelController.createHotel);
router.get('/', hotelController.getAllHotels);
router.get('/:id', hotelController.getHotelById);
router.get('/:id/room-types', hotelController.getRoomTypes);
router.get('/:id/reviews', hotelController.getReviews);
router.post('/lock-room', hotelController.lockRoom);
export default router;
