import 'package:flutter/material.dart';

class AppSettings extends ChangeNotifier {
  static final AppSettings instance = AppSettings._internal();
  AppSettings._internal();

  bool _isDarkMode = false;
  String _locale = 'en';

  bool get isDarkMode => _isDarkMode;
  String get locale => _locale;

  void toggleTheme(bool isDark) {
    _isDarkMode = isDark;
    notifyListeners();
  }

  void setLocale(String newLocale) {
    if (['en', 'vi', 'ru'].contains(newLocale)) {
      _locale = newLocale;
      notifyListeners();
    }
  }

  String translate(String key) {
    final Map<String, Map<String, String>> dict = {
      'en': {
        // Bottom Nav & General
        'Home': 'Home',
        'Saved': 'Saved',
        'Bookings': 'Bookings',
        'Profile': 'Profile',
        'Settings': 'Settings',
        'General': 'General',
        'Language': 'Language',
        'Dark Mode': 'Dark Mode',
        'Push Notifications': 'Push Notifications',
        
        // Home Screen
        'Good morning,': 'Good morning,',
        'Discover': 'Discover',
        'Luxurious stays await you': 'Luxurious stays await you',
        'Where to next?': 'Where to next?',
        'Curated for you': 'Curated for you',
        'Search': 'Search',
        'Map View': 'Map View',
        'from center': 'from center',
        'away': 'away',
        'All': 'All',
        'Popular': 'Popular',
        'See All': 'See All',
        'Hotel': 'Hotel',
        'Resort': 'Resort',
        'Villa': 'Villa',
        'Apartment': 'Apartment',
        'Homestay': 'Homestay',
        
        // Hotel Detail
        'Description': 'Description',
        'Facilities': 'Facilities',
        'Price': 'Price',
        ' / night': ' / night',
        'Book Now': 'Book Now',
        'Free Wifi': 'Free Wifi',
        'Pool': 'Pool',
        'Restaurant': 'Restaurant',
        'Parking': 'Parking',
        
        // Booking Screen
        'Booking Details': 'Booking Details',
        'Check-in - Check-out': 'Check-in - Check-out',
        'Select Dates': 'Select Dates',
        'Guests & Rooms': 'Guests & Rooms',
        'Select Guests': 'Select Guests',
        'Adults': 'Adults',
        'Children': 'Children',
        'Rooms': 'Rooms',
        'Done': 'Done',
        'Total Price': 'Total Price',
        'Pay Now': 'Pay Now',
        'Non-Refundable': 'Non-Refundable',
        'Cancellation is not possible for this rate.': 'Cancellation is not possible for this rate.',
        'Choose Check-in - Check-out Dates': 'Choose Check-in - Check-out Dates',

        // Profile Screen
        'My Profile': 'My Profile',
        'VIP Concierge': 'VIP Concierge',
        'Personal Information': 'Personal Information',
        'Payment Methods': 'Payment Methods',
        'Notifications': 'Notifications',
        'Rewards & Points': 'Rewards & Points',
        'Refer a Friend': 'Refer a Friend',
        'Help Center': 'Help Center',
        'Log Out': 'Log Out',
        
        // Settings Screen
        'Security': 'Security',
        'Change Password': 'Change Password',
        'Two-Factor Authentication': 'Two-Factor Authentication',
        'Face ID / Touch ID': 'Face ID / Touch ID',
        'Terms of Service': 'Terms of Service',
        'Privacy Policy': 'Privacy Policy',
        'Legal': 'Legal',
        'Feature in progress': 'Feature in progress',
        'This feature will be available when Backend is ready!': 'This feature will be available when Backend is ready!',
        'OK': 'OK',
        
        // Saved & Bookings
        'No saved hotels yet.': 'No saved hotels yet.',
        'Start exploring and save your favorites!': 'Start exploring and save your favorites!',
        'Không tìm thấy kết quả nào phù hợp': 'No matching results found',
        'Active': 'Active',
        'Completed': 'Completed',
        'Cancelled': 'Cancelled',
        'Upcoming': 'Upcoming',
        'No upcoming bookings.': 'No upcoming bookings.',
        'No completed bookings.': 'No completed bookings.',
        'No cancelled bookings.': 'No cancelled bookings.',
        'Confirmed': 'Confirmed',
        'CONFIRMED': 'Confirmed',
        'PENDING': 'Pending',
        'COMPLETED': 'Completed',
        'CANCELLED': 'Cancelled',
        'UNPAID': 'Unpaid',
        'PAID': 'Paid',
        'REFUNDING': 'Refunding',
        'REFUNDED': 'Refunded',
        'Refunding': 'Refunding',
        'Refunded': 'Refunded',
        'Paid - Pending': 'Paid - Pending',
        'Unpaid': 'Unpaid',
        'Remove from Saved': 'Remove from Saved',
        'removed from saved list': 'removed from saved list',

        // Booking Detail Screen Extras
        'Booking Status': 'Booking Status',
        'Status': 'Status',
        'Payment': 'Payment',
        'Booking Date': 'Booking Date',
        'Stay Details': 'Stay Details',
        'Check-in': 'Check-in',
        'Check-out': 'Check-out',
        'Continue Payment': 'Continue Payment',
        'Generating payment link...': 'Generating payment link...',
        'Request Cancel & Refund': 'Request Cancel & Refund',
        'Cancel Booking': 'Cancel Booking',
        'Contact Support': 'Contact Support',
        'My Bookings': 'My Bookings',

        // Filter Screen
        'Advanced Filters': 'Advanced Filters',
        'Sort By': 'Sort By',
        'Clear All': 'Clear All',
        'Recommended': 'Recommended',
        'Lowest Price': 'Lowest Price',
        'Highest Price': 'Highest Price',
        'Top Rated': 'Top Rated',
        '1. Basic Information': '1. Basic Information',
        'Price Range (Per Night)': 'Price Range (Per Night)',
        'Minimum Star Rating': 'Minimum Star Rating',
        'Review Score': 'Review Score',
        '2. Location & Distance': '2. Location & Distance',
        'Near Public Transport': 'Near Public Transport',
        'Close to bus station or train station': 'Close to bus station or train station',
        '3. Type & Amenities': '3. Type & Amenities',
        'Popular Amenities': 'Popular Amenities',
        'Room Features': 'Room Features',
        'Policies': 'Policies',
        'Show Results': 'Show Results',
        'Gym': 'Gym',
        'Spa': 'Spa',
        'Free Breakfast': 'Free Breakfast',
        'Free Parking': 'Free Parking',
        'AC': 'AC',
        'Balcony': 'Balcony',
        'Window': 'Window',
        'Bathtub': 'Bathtub',
        'Private Pool': 'Private Pool',
        'Free Cancellation': 'Free Cancellation',
        'No Credit Card': 'No Credit Card',
        'Pay at Hotel': 'Pay at Hotel',
      },
      'vi': {
        // Bottom Nav & General
        'Home': 'Trang chủ',
        'Saved': 'Đã lưu',
        'Bookings': 'Đơn đặt',
        'Profile': 'Hồ sơ',
        'Settings': 'Cài đặt',
        'General': 'Chung',
        'Language': 'Ngôn ngữ',
        'Dark Mode': 'Chế độ tối',
        'Push Notifications': 'Thông báo đẩy',
        
        // Home Screen
        'Good morning,': 'Chào buổi sáng,',
        'Discover': 'Khám phá',
        'Luxurious stays await you': 'Những kỳ nghỉ xa hoa đang chờ bạn',
        'Where to next?': 'Bạn muốn đi đâu?',
        'Curated for you': 'Dành riêng cho bạn',
        'Search': 'Tìm kiếm',
        'Map View': 'Bản đồ',
        'from center': 'cách trung tâm',
        'away': 'cách đây',
        'All': 'Tất cả',
        'Popular': 'Phổ biến',
        'See All': 'Xem tất cả',
        'Hotel': 'Khách sạn',
        'Resort': 'Khu nghỉ dưỡng',
        'Villa': 'Biệt thự',
        'Apartment': 'Căn hộ',
        'Homestay': 'Nhà nghỉ',
        
        // Hotel Detail
        'Description': 'Mô tả',
        'Facilities': 'Tiện nghi',
        'Price': 'Giá',
        ' / night': ' / đêm',
        'Book Now': 'Đặt ngay',
        'Free Wifi': 'Wifi miễn phí',
        'Pool': 'Hồ bơi',
        'Restaurant': 'Nhà hàng',
        'Parking': 'Bãi đỗ xe',
        
        // Booking Screen
        'Booking Details': 'Chi tiết đặt phòng',
        'Dates': 'Ngày đặt',
        'All': 'Tất cả',
        'Check-in': 'Nhận phòng',
        'Check-out': 'Trả phòng',
        'Guests & Rooms': 'Khách & Phòng',
        'Proceed to Payment ': 'Thanh toán ',
        'Reviews': 'Đánh giá',
        'About': 'Giới thiệu',
        'Reserve': 'Đặt phòng',
        'See all': 'Xem tất cả',
        'Select Guests': 'Chọn khách',
        'Adults': 'Người lớn',
        'Children': 'Trẻ em',
        'Rooms': 'Số phòng',
        'Done': 'Xong',
        'Total Price': 'Tổng tiền',
        'Pay Now': 'Thanh toán ngay',
        'Non-Refundable': 'Không hoàn tiền',
        'Cancellation is not possible for this rate.': 'Hủy phòng không được hỗ trợ với mức giá này.',
        'Choose Check-in - Check-out Dates': 'Chọn ngày Nhận và Trả phòng',

        // Profile Screen
        'My Profile': 'Hồ sơ của tôi',
        'VIP Concierge': 'Trợ lý VIP',
        'Personal Information': 'Thông tin cá nhân',
        'Payment Methods': 'Phương thức thanh toán',
        'Notifications': 'Thông báo',
        'Rewards & Points': 'Điểm & Phần thưởng',
        'Refer a Friend': 'Giới thiệu bạn bè',
        'Help Center': 'Trung tâm trợ giúp',
        'Log Out': 'Đăng xuất',
        
        // Settings Screen
        'Security': 'Bảo mật',
        'Change Password': 'Đổi mật khẩu',
        'Two-Factor Authentication': 'Xác thực 2 bước',
        'Face ID / Touch ID': 'Sinh trắc học',
        'Terms of Service': 'Điều khoản dịch vụ',
        'Privacy Policy': 'Chính sách bảo mật',
        'Legal': 'Pháp lý',
        'Feature in progress': 'Tính năng đang phát triển',
        'This feature will be available when Backend is ready!': 'Tính năng này sẽ hoàn thiện khi kết nối Backend!',
        'OK': 'Đồng ý',
        
        // Saved & Bookings
        'No saved hotels yet.': 'Chưa có khách sạn nào.',
        'Start exploring and save your favorites!': 'Hãy khám phá và lưu lại những nơi bạn yêu thích!',
        'Không tìm thấy kết quả nào phù hợp': 'Không tìm thấy kết quả nào phù hợp',
        'Active': 'Hiện tại',
        'Completed': 'Đã đi',
        'Cancelled': 'Đã hủy',
        'Upcoming': 'Sắp tới',
        'No upcoming bookings.': 'Không có đơn đặt sắp tới.',
        'No completed bookings.': 'Không có đơn đặt đã hoàn thành.',
        'No cancelled bookings.': 'Không có đơn đặt đã hủy.',
        'Confirmed': 'Đã xác nhận',
        'CONFIRMED': 'Đã xác nhận',
        'PENDING': 'Chờ xử lý',
        'COMPLETED': 'Đã hoàn thành',
        'CANCELLED': 'Đã hủy',
        'UNPAID': 'Chưa thanh toán',
        'PAID': 'Đã thanh toán',
        'REFUNDING': 'Đang hoàn tiền',
        'REFUNDED': 'Đã hoàn tiền',
        'Refunding': 'Đang hoàn tiền',
        'Refunded': 'Đã hoàn tiền',
        'Paid - Pending': 'Đã thanh toán - Chờ xử lý',
        'Unpaid': 'Chưa thanh toán',
        'Remove from Saved': 'Xóa khỏi Đã lưu',
        'removed from saved list': 'đã xóa khỏi danh sách lưu',

        // Booking Detail Screen Extras
        'Booking Status': 'Trạng thái Đơn',
        'Status': 'Trạng thái',
        'Payment': 'Thanh toán',
        'Booking Date': 'Ngày đặt',
        'Stay Details': 'Chi tiết kỳ nghỉ',
        'Check-in': 'Nhận phòng',
        'Check-out': 'Trả phòng',
        'Continue Payment': 'Tiếp tục thanh toán',
        'Generating payment link...': 'Đang tạo link thanh toán...',
        'Request Cancel & Refund': 'Yêu cầu Hủy & Hoàn tiền',
        'Cancel Booking': 'Hủy Đơn',
        'Contact Support': 'Liên hệ CSKH',
        'My Bookings': 'Đơn đặt của tôi',

        // Filter Screen
        'Advanced Filters': 'Bộ lọc Nâng cao',
        'Sort By': 'Sắp xếp theo',
        'Clear All': 'Xóa tất cả',
        'Recommended': 'Đề xuất',
        'Lowest Price': 'Giá thấp nhất',
        'Highest Price': 'Giá cao nhất',
        'Top Rated': 'Đánh giá cao',
        '1. Basic Information': '1. Thông tin Cơ bản',
        'Price Range (Per Night)': 'Mức giá (Mỗi đêm)',
        'Minimum Star Rating': 'Xếp hạng sao tối thiểu',
        'Review Score': 'Điểm đánh giá',
        '2. Location & Distance': '2. Vị trí & Khoảng cách',
        'Near Public Transport': 'Gần phương tiện công cộng',
        'Close to bus station or train station': 'Gần bến xe hoặc ga tàu',
        '3. Type & Amenities': '3. Loại hình & Tiện nghi',
        'Popular Amenities': 'Tiện nghi Phổ biến',
        'Room Features': 'Đặc điểm Phòng',
        'Policies': 'Chính sách',
        'Show Results': 'Hiển thị Kết quả',
        'Gym': 'Phòng Gym',
        'Spa': 'Spa',
        'Free Breakfast': 'Bữa sáng Miễn phí',
        'Free Parking': 'Đỗ xe Miễn phí',
        'AC': 'Điều hòa',
        'Balcony': 'Ban công',
        'Window': 'Cửa sổ',
        'Bathtub': 'Bồn tắm',
        'Private Pool': 'Hồ bơi Riêng',
        'Free Cancellation': 'Hủy Miễn phí',
        'No Credit Card': 'Không cần Thẻ tín dụng',
        'Pay at Hotel': 'Thanh toán tại Khách sạn',
      },
      'ru': {
        // Bottom Nav & General
        'Home': 'Главная',
        'Saved': 'Сохранено',
        'Bookings': 'Бронирования',
        'Profile': 'Профиль',
        'Settings': 'Настройки',
        'General': 'Общее',
        'Language': 'Язык',
        'Dark Mode': 'Темный режим',
        'Push Notifications': 'Уведомления',
        
        // Home Screen
        'Good morning,': 'Доброе утро,',
        'Discover': 'Исследовать',
        'Luxurious stays await you': 'Вас ждут роскошные отели',
        'Where to next?': 'Куда вы хотите поехать?',
        'Curated for you': 'Специально для вас',
        'Search': 'Поиск',
        'Map View': 'Карта',
        'from center': 'от центра',
        'away': 'отсюда',
        'All': 'Все',
        'Popular': 'Популярные',
        'See All': 'Смотреть все',
        'Hotel': 'Отель',
        'Resort': 'Курорт',
        'Villa': 'Вилла',
        'Apartment': 'Квартира',
        'Homestay': 'Семья',
        
        // Hotel Detail
        'Description': 'Описание',
        'Facilities': 'Удобства',
        'Price': 'Цена',
        ' / night': ' / ночь',
        'Book Now': 'Забронировать',
        'Free Wifi': 'Бесплатный Wifi',
        'Pool': 'Бассейн',
        'Restaurant': 'Ресторан',
        'Parking': 'Парковка',
        
        // Booking Screen
        'Booking Details': 'Детали бронирования',
        'Check-in - Check-out': 'Заезд - Выезд',
        'Select Dates': 'Выберите даты',
        'Guests & Rooms': 'Гости и номера',
        'Select Guests': 'Выберите гостей',
        'Adults': 'Взрослые',
        'Children': 'Дети',
        'Rooms': 'Номера',
        'Done': 'Готово',
        'Total Price': 'Итоговая цена',
        'Pay Now': 'Оплатить сейчас',
        'Non-Refundable': 'Безвозвратный',
        'Cancellation is not possible for this rate.': 'Отмена невозможна по этому тарифу.',
        'Choose Check-in - Check-out Dates': 'Выберите даты заезда и выезда',

        // Profile Screen
        'My Profile': 'Мой профиль',
        'VIP Concierge': 'VIP-консьерж',
        'Personal Information': 'Личная информация',
        'Payment Methods': 'Способы оплаты',
        'Notifications': 'Уведомления',
        'Rewards & Points': 'Награды и баллы',
        'Refer a Friend': 'Пригласить друга',
        'Help Center': 'Справочный центр',
        'Log Out': 'Выйти',
        
        // Settings Screen
        'Security': 'Безопасность',
        'Change Password': 'Изменить пароль',
        'Two-Factor Authentication': 'Двухфакторная аутентификация',
        'Face ID / Touch ID': 'Face ID / Touch ID',
        'Terms of Service': 'Условия предоставления услуг',
        'Privacy Policy': 'Политика конфиденциальности',
        'Legal': 'Юридический',
        'Feature in progress': 'Функция в разработке',
        'This feature will be available when Backend is ready!': 'Эта функция будет доступна, когда Backend будет готов!',
        'OK': 'ОК',
        
        // Saved & Bookings
        'No saved hotels yet.': 'Пока нет сохраненных отелей.',
        'Start exploring and save your favorites!': 'Начните исследовать и сохраняйте любимые места!',
        'Không tìm thấy kết quả nào phù hợp': 'Подходящих результатов не найдено',
        'Active': 'Активный',
        'Completed': 'Завершенный',
        'Cancelled': 'Отменен',
        'Upcoming': 'Предстоящие',
        'No upcoming bookings.': 'Нет предстоящих бронирований.',
        'No completed bookings.': 'Нет завершенных бронирований.',
        'No cancelled bookings.': 'Нет отмененных бронирований.',
        'Confirmed': 'Подтвержден',
        'CONFIRMED': 'Подтвержден',
        'PENDING': 'В ожидании',
        'COMPLETED': 'Завершенный',
        'CANCELLED': 'Отменен',
        'UNPAID': 'Не оплачено',
        'PAID': 'Оплачено',
        'REFUNDING': 'Возврат средств',
        'REFUNDED': 'Возвращено',
        'Refunding': 'Возврат средств',
        'Refunded': 'Возвращено',
        'Paid - Pending': 'Оплачено - В ожидании',
        'Unpaid': 'Не оплачено',
        'Remove from Saved': 'Удалить из сохраненных',
        'removed from saved list': 'удалено из списка сохраненных',

        // Booking Detail Screen Extras
        'Booking Status': 'Статус бронирования',
        'Status': 'Статус',
        'Payment': 'Оплата',
        'Booking Date': 'Дата бронирования',
        'Stay Details': 'Детали проживания',
        'Check-in': 'Заезд',
        'Check-out': 'Выезд',
        'Continue Payment': 'Продолжить оплату',
        'Generating payment link...': 'Создание ссылки для оплаты...',
        'Request Cancel & Refund': 'Запрос на отмену и возврат',
        'Cancel Booking': 'Отменить бронирование',
        'Contact Support': 'Связаться с поддержкой',
        'My Bookings': 'Мои бронирования',

        // Filter Screen
        'Advanced Filters': 'Расширенные фильтры',
        'Sort By': 'Сортировать по',
        'Clear All': 'Очистить все',
        'Recommended': 'Рекомендуемые',
        'Lowest Price': 'Самая низкая цена',
        'Highest Price': 'Самая высокая цена',
        'Top Rated': 'С высоким рейтингом',
        '1. Basic Information': '1. Основная информация',
        'Price Range (Per Night)': 'Диапазон цен (за ночь)',
        'Minimum Star Rating': 'Минимальное количество звезд',
        'Review Score': 'Оценка по отзывам',
        '2. Location & Distance': '2. Расположение и расстояние',
        'Near Public Transport': 'Рядом с остановками',
        'Close to bus station or train station': 'Близко к автовокзалу или ж/д станции',
        '3. Type & Amenities': '3. Тип и удобства',
        'Popular Amenities': 'Популярные удобства',
        'Room Features': 'Особенности номеров',
        'Policies': 'Правила',
        'Show Results': 'Показать результаты',
        'Gym': 'Тренажерный зал',
        'Spa': 'Спа',
        'Free Breakfast': 'Бесплатный завтрак',
        'Free Parking': 'Бесплатная парковка',
        'AC': 'Кондиционер',
        'Balcony': 'Балкон',
        'Window': 'Окно',
        'Bathtub': 'Ванна',
        'Private Pool': 'Собственный бассейн',
        'Free Cancellation': 'Бесплатная отмена',
        'No Credit Card': 'Без кредитной карты',
        'Pay at Hotel': 'Оплата в отеле',
      },
    };

    return dict[_locale]?[key] ?? key;
  }
}

String tr(String key) {
  return AppSettings.instance.translate(key);
}
